//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievements
    {
        public int idAchievements { get; set; }
        public string achievementTitle { get; set; }
        public string achievementsDescription { get; set; }
        public string achievementRarity { get; set; }
        public int Player_idPlayer { get; set; }
        public Nullable<System.DateTime> achievementDate { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
