//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvatarsUnlocked
    {
        public int Player_idPlayer { get; set; }
        public int Avatar_idAvatar { get; set; }
        public Nullable<System.DateTime> unlockedDate { get; set; }
    
        public virtual Avatar Avatar { get; set; }
        public virtual Player Player { get; set; }
    }
}
