//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avatar()
        {
            this.AvatarsUnlocked = new HashSet<AvatarsUnlocked>();
        }
    
        public int idAvatar { get; set; }
        public string avatarName { get; set; }
        public string avatarDescription { get; set; }
        public string avatarRarity { get; set; }
        public Nullable<int> LootBoxType_idLootBoxType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvatarsUnlocked> AvatarsUnlocked { get; set; }
        public virtual LootBoxType LootBoxType { get; set; }
    }
}
