//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LootBoxType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LootBoxType()
        {
            this.Avatar = new HashSet<Avatar>();
        }
    
        public int idLootBoxType { get; set; }
        public string boxName { get; set; }
        public string boxRarity { get; set; }
        public int price { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avatar> Avatar { get; set; }
    }
}
