//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UNOContext : DbContext
    {
        public UNOContext()
            : base("name=UNOContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Achievements> Achievements { get; set; }
        public virtual DbSet<Avatar> Avatar { get; set; }
        public virtual DbSet<AvatarsUnlocked> AvatarsUnlocked { get; set; }
        public virtual DbSet<FriendList> FriendList { get; set; }
        public virtual DbSet<LootBoxType> LootBoxType { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerStatistics> PlayerStatistics { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Sanction> Sanction { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetwork { get; set; }
    }
}
