//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStatistics
    {
        public int idPlayerStatistics { get; set; }
        public Nullable<int> matchesPlayed { get; set; }
        public Nullable<int> wins { get; set; }
        public Nullable<int> loses { get; set; }
        public Nullable<int> globalPoints { get; set; }
        public Nullable<int> streak { get; set; }
        public Nullable<int> maxStreak { get; set; }
        public int Player_idPlayer { get; set; }
        public Nullable<int> MatchGame_idMatchGame { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
