//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int idReport { get; set; }
        public int Player_idPlayer { get; set; }
        public string reportDescription { get; set; }
        public Nullable<System.DateTime> reportDate { get; set; }
        public int ReportedPlayer_idPlayer { get; set; }
        public int ReporterPlayer_idPlayer { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player11 { get; set; }
    }
}
