//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanction
    {
        public int idSanction { get; set; }
        public string sanctionType { get; set; }
        public string sanctionDescription { get; set; }
        public Nullable<System.DateTime> sanctionDate { get; set; }
        public int Player_idPlayer { get; set; }
        public Nullable<System.DateTime> sanctionStartDate { get; set; }
        public Nullable<System.DateTime> sanctionEndDate { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
