//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialNetwork
    {
        public int idRedSocial { get; set; }
        public string tipoRedSocial { get; set; }
        public string linkRedSocial { get; set; }
        public int Player_idPlayer { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
